# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "gcollic/DockerAspNet"
  config.vm.box_check_update = false
  config.vm.provider "hyperv"
  config.vm.synced_folder "../demos", "/demos"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
